fix up actions
Squashed commit of the following:

commit 5f386c2c450656b89895c06d849113680866c659
Author: ryane <ryanesc@gmail.com>
Date:   Sat Jun 3 07:10:00 2023 -0400

    restore tags constraint on releaser action

commit f37cbd69f835c99ae8feef7daaa5bf6a2a996f91
Author: ryane <ryanesc@gmail.com>
Date:   Sat Jun 3 07:02:44 2023 -0400

    fix go version

commit ba0536cfeab949da804477d2fc7b1d95cb2db333
Author: ryane <ryanesc@gmail.com>
Date:   Fri Jun 2 06:58:05 2023 -0400

    add build cache?

commit 9d5674c39fcebbac9fa9a8fa7eaee439c104f9ca
Author: ryane <ryanesc@gmail.com>
Date:   Fri Jun 2 06:56:26 2023 -0400

    troubleshoot actions

    ```
      • running before hooks
        • running                                        hook=go mod download
      ⨯ release failed after 0s                  error=hook failed: go mod download: exit status 2; output: go: unknown subcommand "mod"
    Run 'go help' for usage.

    Error: The process '/opt/hostedtoolcache/goreleaser-action/1.18.2/x64/goreleaser' failed with exit code 1
    ```